In [28]:
import torch
import torch.nn as nn

## Шаг 3
Примените свёртку с ядром (−0.5,0,0.5) к сигналу (1,1,2,3,3,3,2,1,1). Ответ запишите в виде последовательности чисел, разделённых пробелами. В качестве десятичного разделителя используйте точку. Входную последовательность не нужно дополнять фиктивными элементами (padding выключен).

Шаг свёртки (stride в PyTorch) считаем 1.

In [29]:
# x = torch.Tensor([1, 1, 2, 3, 3, 3, 2, 1, 1]).unsqueeze(0)
# print(x.shape)
# print(x)
# # x = torch.transpose(x, 1, 0)
# print(x.shape)
# print(x)

# kernel = torch.Tensor([[-0.5, 0, 0.5],
#                       [0, 0, 0]]).unsqueeze(0)
# print(kernel.shape)
# print(kernel)

# y = nn.functional.conv1d(x, kernel)
# print('answer:')
# print(y)

## Шаг 5
Оцените ширину рецептивного поля для нейросети, состоящей из 4 свёрточных слоёв с ядром 5, соединённых последовательно. Код на PyTorch для создания такой нейросети:
```
nn.Sequential(
    nn.Conv1d(in_channels=1, out_channels=1, kernel_size=5),
    nn.Conv1d(in_channels=1, out_channels=1, kernel_size=5),
    nn.Conv1d(in_channels=1, out_channels=1, kernel_size=5),
    nn.Conv1d(in_channels=1, out_channels=1, kernel_size=5)
)
```
Ширина рецептивного поля - наибольшее расстояние между элементами входной последовательности, которые могут влиять на один и тот же элемент выходной последовательности, плюс один.

Например, ширина рецептивного поля для одного свёрточного блока с ядром 3 равна 3. Для двух таких блоков, соединённых последовательно - 5.

In [30]:
def receptive_field(size_kernel, count_layers):
    return size_kernel + (size_kernel - 1)*(count_layers - 1)

receptive_field(5, 4)

17

## Шаг 6
Примените свёртку к входной последовательности, в которой каждый элемент кодируется вектором размерности 2 (часть 1)

In [31]:
x = torch.Tensor([[1, 0],
                 [1, 1],
                 [0, 0],
                 [0, 1],
                 [1, 0]])
print(x.shape)
print(x)
x = torch.transpose(x, 1, 0)
print(x.shape)
print(x)

torch.Size([5, 2])
tensor([[1., 0.],
        [1., 1.],
        [0., 0.],
        [0., 1.],
        [1., 0.]])
torch.Size([2, 5])
tensor([[1., 1., 0., 0., 1.],
        [0., 1., 0., 1., 0.]])


In [32]:
kernel = torch.Tensor([[1, 1, 0],
                    [0, 1, 1]]).unsqueeze(0)
print(kernel.shape)
print(kernel)

y = nn.functional.conv1d(x, kernel)
print('answer:')
print(y)

torch.Size([1, 2, 3])
tensor([[[1., 1., 0.],
         [0., 1., 1.]]])
answer:
tensor([[3., 2., 1.]])


## Шаг 7
Примените свёртку к входной последовательности, в которой каждый элемент кодируется вектором размерности 2. (часть 2)

In [42]:
input = torch.Tensor([[1, 0],
                 [1, 1],
                 [0, 0],
                 [0, 1],
                 [1, 0]])
print(input.shape)
print(input)
input = torch.transpose(input, 1, 0)
print(input.shape)
print(input)

torch.Size([5, 2])
tensor([[1., 0.],
        [1., 1.],
        [0., 0.],
        [0., 1.],
        [1., 0.]])
torch.Size([2, 5])
tensor([[1., 1., 0., 0., 1.],
        [0., 1., 0., 1., 0.]])


In [44]:
kernel = torch.Tensor([[1, 1, 0],
                       [0, 1, 1], 
                       [1, 0, 0],
                       [0, 0, 1]])
print(kernel.shape)
print(kernel)
kernel = kernel.view(2, 2, 3)
print(kernel.shape)
print(kernel)

torch.Size([4, 3])
tensor([[1., 1., 0.],
        [0., 1., 1.],
        [1., 0., 0.],
        [0., 0., 1.]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 0.],
         [0., 1., 1.]],

        [[1., 0., 0.],
         [0., 0., 1.]]])


In [47]:
output = nn.functional.conv1d(input, kernel)
output.transpose(-2, 1)

tensor([[3., 1.],
        [2., 2.],
        [1., 0.]])

## Шаг 8
Оцените количество параметров в свёрточном блоке, принимающем 64 канала, возвращающем 128 каналов, длина ядра 5. Не забывайте про параметры сдвига (bias, их количество соответствует количеству выходных каналов).

Размер свертки n x m.  l=64 feature maps в качестве ввода,k=128 feature maps в качестве вывода, а размер фильтра -n=5 x m=1.  Таким образом, общее количество весов -n*m*k*l. Тогда есть также термин смещения для каждой карты объектов, поэтому у нас есть общее количество параметров (n*m*l+1)*k.

Нужно просто посмотреть на формулу свертки в предыдущем задании
(k*in+1)*out
k-длина ядра, in - входной канал, out - выходной канал

In [49]:
(5*1*64+1)*128

41088